version: '3.8'

services:
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_db
    ports:
      - "3310:3306"
    networks:
      - app-network

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_db
    ports:
      - "3311:3306"
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-order
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: order_db
      INVENTORY_SERVICE_URL: http://inventory-service:3001
      SIMULATE_CRASH: "true"
    depends_on:
      - mysql-order
      - inventory-service
    networks:
      - app-network

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql-inventory
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: inventory_db
    depends_on:
      - mysql-inventory
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_ORDER_SERVICE_URL=http://localhost:3000
      - VITE_INVENTORY_SERVICE_URL=http://localhost:3001
    depends_on:
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
